{"name": "test_mult[字符串乘于正数异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "11"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603368606378, "stop": 1603368606379, "uuid": "6686855c-6e8e-4bf2-aab2-c12499e73149", "historyId": "9d3ea29a043334757d9bfd12a58275dc", "testCaseId": "46d692343060e5716c895bdf2d9d56eb", "fullName": "test_calc2.TestCalcTaskOne#test_mult", "labels": [{"name": "tag", "value": "mult"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc2"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "50460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc2"}]}