{"name": "test_mult[字符串乘于正数异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "11"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603368606576, "stop": 1603368606576, "uuid": "aac65216-30f4-4313-9f2d-7aabdd9ea0e4", "historyId": "d546bd83338dbc0b39572c88aea12838", "testCaseId": "5ba7137ceb70f9037bb50d3c2be4f3da", "fullName": "test_calc1.TestCalcTaskOne#test_mult", "labels": [{"name": "tag", "value": "mult"}, {"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc1"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "50460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc1"}]}