{"name": "test_mult[字符串乘于正数异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "11"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603377912286, "stop": 1603377912287, "uuid": "46aa8134-46eb-4296-a6e5-599a18dc638f", "historyId": "d546bd83338dbc0b39572c88aea12838", "testCaseId": "5ba7137ceb70f9037bb50d3c2be4f3da", "fullName": "test_calc1.TestCalcTaskOne#test_mult", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "tag", "value": "mult"}, {"name": "suite", "value": "test_calc1"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "2038-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc1"}]}